### ISSUE TITLE
Put install instructions in README.md

### ISSUE THREAD

**Issue by jamesrward** [kalabox/kalabox-ui#114]
Either add some install instructions to the README.md or just add a link to http://api.kalabox.me/ if you intend to maintain the instructions there.  I don't think ```npm install kalabox -g``` is an obvious install method for those not familiar with the project.

**Comment by pirog** [comment]
Were you trying to install this project or the CLI version of Kalabox? This project doesn't do much at this point but we'll be working in it in the coming months.

**Comment by jamesrward** [comment]
Aha.  I was just trying to install kalabox and thought this was the newest version.  I see now I was in the wrong repository entirely and should have been at https://github.com/kalabox/kalabox.  Doh!
