### ISSUE TITLE
Logical defaults when adding new site from Pantheon

### ISSUE THREAD

**Issue by fluxsauce** [kalabox/kalabox-ui#185]
- Click "Add new site"
- Name Your App:
  - Expected: Default to Pantheon site name
  - Actual: `(Blank)`
- Which environment?
  - Expected: Default to Dev environment
  - Actual: `-- Select Environment --`

**Comment by pirog** [comment]
Great feedback but can you post over at the main kalabox/kalabox repo?

**Comment by fluxsauce** [comment]
Absolutely.
